### ISSUE TITLE
Sorting is not enable for ALL Search/List Page under

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/ZIMS-School-Mgmt#217]
Please check and rectify

**Comment by kvora** [comment]
@mnarewec - we have sorting functionality on each list page. In this screen shot - http://screencast.com/t/WHTDdCEWh - I have highlighted sorting functionality. Please verify

**Comment by mnarewec** [comment]
I like the functionality where you click on the Column Headers and it will sort. Like the ones implemented in KBS

**Comment by AAndharia** [comment]
Marsh, we already discussed about this at the begining before implementing in all pages and you confirmed to do it this way ... changing it would be a big change and a CR.

**Comment by mnarewec** [comment]
@AAndharia I only confirm that sort should happen but did not confirm any implementation technique and I assume at that time that sort will be like KBS.

**Comment by AAndharia** [comment]
@mnarewec  - here is our chat history.


Amit Andharia
you mean you agree with me?
Marsh Narewec
No especailly the sort feature can we keep it the same as KSB?
Amit Andharia
Ok, we'll make that change
just put your comment in github
but believe me what we did is better one
Marsh Narewec
ok will do
Amit Andharia
more userfriendly
that's what other clients/people are asking these days
instead of old/traditional sorting feature
still if you wish, we'll change it
can you please put your comments right away, so that we can start working around..
on both of those points in ZIMS
Marsh Narewec
ok forget it then..lets stick to the new standards

**Comment by mnarewec** [comment]
@AAndharia ..ah ah ..
![image](https://cloud.githubusercontent.com/assets/10192106/5987765/e53faee0-a989-11e4-9ad2-ab2fdea9b639.png)

I wish for you to change it. I don't like it.

**Comment by mnarewec** [comment]
ok, This issue is considered closed.
